'use client'

import { useState } from 'react'
import { ArrowUpRight, ChevronDown, Menu, Play, Sparkles, X } from 'lucide-react'
import { RegistrationForm } from '@/components/registration-form'

const media = {
  hero: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_6499%202.JPG-LOuo1XR26mn94dudzTkRttnJ2i2aLE.jpeg',
  group: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_6647%202.PNG-solOiG8IYiwKyirNW0JGRqWOyZhzZu.png',
  action: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_4977.JPG-O2JYdGzbM4zlTzR5HiE4mV0Du0mcz8.jpeg',
  training: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_5583.JPG-oPSA6xpJZJvX7ieGgauwI0PefEYm6j.jpeg',
  afa: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/AZUL3-AFA-INTERNACIONAL-F6CyzCFMMlPDVbfycN99TW6FH0wsHp.png',
  tm: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/TMX03-EAooAO1aeAIX89uIBy2tHqAKWeljAY.png',
  coach: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_6533.JPG-E5s0aYaukfU3PrjdvV2lAFh84OJOsh.jpeg',
  sideline: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/DSC06610-Tbs2dGoPbt5P8TapOcMPtnuM2293vo.jpg',
  sponsorStrip: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-5R1qzOaXxuBP7Ok6o44x5LECcPZzvL.png',
}

const faqs = [
  ['¿Qué incluye la experiencia?', 'Entrenamientos AFA Internacional, actividades de equipo, acompañamiento profesional, hidratación, snacks, seguro y diploma de reconocimiento.'],
  ['¿Quiénes pueden participar?', 'Niños y jóvenes apasionados por el fútbol, organizados por edades y niveles para que cada jugador tenga el reto correcto.'],
  ['¿Cómo reservo un cupo?', 'Escríbenos por WhatsApp o Instagram. Te enviaremos las fechas, disponibilidad y todo lo que necesitas para inscribirte.'],
]

export default function Page() {
  const [openFaq, setOpenFaq] = useState(0)
  const [menuOpen, setMenuOpen] = useState(false)
  const [registrationCity, setRegistrationCity] = useState<'Caracas' | 'Valencia' | null>(null)
  const closeMenu = () => setMenuOpen(false)

  return (
    <main>
      <header className="header">
        <a className="header-brand" href="#inicio" aria-label="Camp Experience Vzla"><img src={media.afa} alt="AFA Internacional" /><span className="header-rule" /><img className="tm-logo" src={media.tm} alt="TMXperience" /></a>
        <button className="mobile-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Cerrar menú' : 'Abrir menú'} aria-expanded={menuOpen}>{menuOpen ? <X /> : <Menu />}</button>
        <nav className={menuOpen ? 'nav nav-open' : 'nav'} aria-label="Navegación principal"><a href="#nosotros" onClick={closeMenu}>Nosotros</a><a href="#programa" onClick={closeMenu}>Programa</a><a href="#cronograma" onClick={closeMenu}>Cronograma</a><a href="#sedes" onClick={closeMenu}>Sedes</a><a href="#patrocinantes" onClick={closeMenu}>Patrocinantes</a><a href="#contenido" onClick={closeMenu}>Contenido</a><a className="nav-button" href="#contacto" onClick={closeMenu}>Reserva tu cupo <ArrowUpRight /></a></nav>
      </header>

      <section id="inicio" className="hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(3,20,42,.98) 0%, rgba(3,20,42,.78) 37%, rgba(3,20,42,.08) 78%), url(${media.hero})` }}>
        <div className="hero-content frame"><div className="hero-kicker"><Sparkles /> Venezuela · AFA Internacional</div><h1>Entrena como<br /><span>los campeones.</span></h1><p>Una experiencia de fútbol que forma jugadores, fortalece equipos y deja historias para siempre.</p><div className="hero-actions"><a className="button orange" href="#contacto">Quiero estar ahí <ArrowUpRight /></a><a className="hero-link" href="#nosotros">Conoce Camp Experience <span>↓</span></a></div></div><div className="hero-scroll">Desliza para descubrir <span>↓</span></div><div className="hero-stars" aria-hidden="true">✦<br />✦</div>
      </section>
      <div className="ticker" aria-hidden="true"><span>Fútbol · amistad · disciplina · experiencia · fútbol · amistad · disciplina · experiencia · </span></div>

      <section id="nosotros" className="about frame section-space"><div className="section-label">01 / Nosotros</div><div className="about-grid"><div><h2>Donde comienza<br /><i>el futuro.</i></h2></div><div className="about-copy"><p className="big-copy">Más que unas vacaciones: un espacio real de crecimiento.</p><p>Camp Experience nace para elevar el estándar del fútbol juvenil en Venezuela. Conectamos a niños y jóvenes con una metodología inspirada en el más alto nivel, guiada por entrenadores certificados y una comunidad que cree en el poder del deporte.</p><a className="under-link" href="#programa">Conoce la experiencia <ArrowUpRight /></a></div></div><div className="about-image" style={{ backgroundImage: `url(${media.group})` }}><div className="image-note">Pasión que se entrena.<br /><strong>Carácter que se construye.</strong></div></div></section>

      <section id="programa" className="program-section"><div className="program-inner frame"><div className="program-photo" style={{ backgroundImage: `url(${media.training})` }}><span className="photo-tag">Entrenamiento real</span></div><div className="program-copy"><div className="section-label blue">02 / Lo que vas a vivir</div><h2>Juega.<br /><i>Aprende.</i><br />Conecta.</h2><p>Cada día está diseñado para que salgas de la cancha siendo un jugador y una persona más completa.</p><div className="program-list"><div><b>01</b><span><strong>Metodología AFA</strong> Entrenamientos con visión internacional.</span></div><div><b>02</b><span><strong>Competencia real</strong> Retos para despertar tu mejor versión.</span></div><div><b>03</b><span><strong>Equipo para siempre</strong> Amigos, valores y momentos que permanecen.</span></div></div></div></div></section>

      <section id="cronograma" className="schedule frame section-space"><div className="section-label">03 / Cronograma</div><div className="schedule-heading"><h2>Una semana<br /><i>que se vive.</i></h2><p>Todo está pensado para que cada jornada tenga movimiento, aprendizaje y momentos que se quedan.</p></div><div className="schedule-grid"><div className="schedule-intro"><span>La experiencia incluye</span><strong>5 o 10 días<br />de fútbol.</strong><p>Un programa completo con entrenamientos, descanso, hidratación y actividades para disfrutar dentro y fuera de la cancha.</p></div><div className="schedule-items"><div><b>01</b><span>Entrenamiento técnico y táctico</span></div><div><b>02</b><span>5 horas de preparación al día</span></div><div><b>03</b><span>Entrenadores oficiales de AFA Internacional</span></div><div><b>04</b><span>Hidratación, snacks y seguro</span></div><div><b>05</b><span>Diploma de reconocimiento</span></div></div></div></section>

      <section id="sedes" className="frame section-space" style={{ background: 'var(--navy)', color: '#fff', borderRadius: '28px', padding: 'clamp(28px, 5vw, 68px)', overflow: 'hidden', position: 'relative' }}><div style={{ position: 'absolute', right: '-8%', top: '-35%', width: '42%', aspectRatio: '1', borderRadius: '999px', background: 'rgba(143,211,246,.12)' }} /><div className="section-label" style={{ position: 'relative' }}>04 / Próximas sedes</div><div style={{ position: 'relative', display: 'flex', justifyContent: 'space-between', alignItems: 'end', gap: '32px', flexWrap: 'wrap', marginTop: '18px' }}><div><h2 style={{ color: '#fff', marginBottom: '14px' }}>La experiencia<br /><i style={{ color: 'var(--sky)' }}>llega más lejos.</i></h2><p style={{ maxWidth: '520px', color: 'rgba(255,255,255,.72)', margin: 0 }}>Prepárate para vivir Camp Experience en dos ciudades. Muy pronto anunciaremos las fechas, sedes y cupos disponibles.</p></div><a className="button orange" href="#contacto">Quiero recibir novedades <ArrowUpRight /></a></div><div style={{ position: 'relative', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '14px', marginTop: '40px' }}><button type="button" onClick={() => setRegistrationCity('Caracas')} style={{ textAlign: 'left', border: '1px solid rgba(255,255,255,.2)', borderRadius: '20px', padding: '24px', background: 'rgba(255,255,255,.06)', color: '#fff', cursor: 'pointer' }}><span style={{ display: 'block', color: 'var(--orange)', fontSize: '11px', fontWeight: 800, letterSpacing: '.14em', marginBottom: '42px' }}>SEDE 01 · INSCRIPCIONES</span><strong style={{ display: 'block', fontFamily: "'Big Shoulders Display', sans-serif", fontSize: 'clamp(2rem, 5vw, 3.5rem)', lineHeight: .9 }}>Caracas</strong><span style={{ display: 'block', color: 'rgba(255,255,255,.58)', marginTop: '12px' }}>Completar formulario →</span></button><button type="button" onClick={() => setRegistrationCity('Valencia')} style={{ textAlign: 'left', border: '1px solid rgba(255,255,255,.2)', borderRadius: '20px', padding: '24px', background: 'rgba(255,255,255,.06)', color: '#fff', cursor: 'pointer' }}><span style={{ display: 'block', color: 'var(--orange)', fontSize: '11px', fontWeight: 800, letterSpacing: '.14em', marginBottom: '42px' }}>SEDE 02 · INSCRIPCIONES</span><strong style={{ display: 'block', fontFamily: "'Big Shoulders Display', sans-serif", fontSize: 'clamp(2rem, 5vw, 3.5rem)', lineHeight: .9 }}>Valencia</strong><span style={{ display: 'block', color: 'rgba(255,255,255,.58)', marginTop: '12px' }}>Completar formulario →</span></button></div></section>

      <section className="photo-showcase frame section-space"><div className="photo-showcase-copy"><div className="section-label">05 / Desde la cancha</div><h2>Personas que<br /><i>hacen historia.</i></h2><p>El camp también se vive en los detalles: una indicación, una mirada y el próximo reto compartido.</p></div><div className="photo-showcase-grid"><div className="showcase-photo" style={{ backgroundImage: `url(${media.coach})` }} role="img" aria-label="Entrenadores y jugadores en la cancha" /><div className="showcase-photo offset" style={{ backgroundImage: `url(${media.sideline})` }} role="img" aria-label="Entrenador acompañando a los jugadores" /></div></section>

      <section id="patrocinantes" className="sponsors-section frame section-space"><div className="section-label">06 / Patrocinantes</div><div className="sponsors-heading"><div><h2>Quienes hacen<br /><i>posible el camp.</i></h2></div><p>Una experiencia de este nivel se construye en equipo. Aquí estarán los aliados que creen en el fútbol venezolano.</p></div><div className="sponsor-strip"><img src={media.sponsorStrip} alt="Logos de patrocinantes y aliados de Camp Experience" /></div><div className="sponsor-logo-grid"><div className="sponsor-logo-card"><img src={media.afa} alt="AFA Internacional" /><span>Metodología oficial</span></div><div className="sponsor-logo-card"><img src={media.tm} alt="TMXperience" /><span>Producción y experiencia</span></div><div className="sponsor-logo-card sponsor-placeholder"><span>Tu marca</span><small>Espacio disponible para patrocinante</small></div><div className="sponsor-logo-card sponsor-placeholder"><span>Tu marca</span><small>Espacio disponible para patrocinante</small></div></div></section>

      <section className="proof frame"><div className="proof-number">+500</div><div><span>JUGADORES</span><strong>ya vivieron<br />la experiencia.</strong></div><div className="proof-divider" /><div className="proof-number">100%</div><div><span>ENERGÍA</span><strong>en cada<br />entrenamiento.</strong></div></section>

      <section id="contenido" className="video-section"><div className="frame"><div className="video-heading"><div><div className="section-label blue">04 / Contenido real</div><h2>Esto no se<br /><i>cuenta.</i><br />Se vive.</h2></div><p>Sube aquí tus videos, reels y momentos favoritos del camp. La cancha también cuenta historias.</p></div><a className="video-card" href="https://www.instagram.com/campexperienceve/" target="_blank" rel="noreferrer" aria-label="Ver contenido de Camp Experience en Instagram"><div className="video-image" style={{ backgroundImage: `linear-gradient(180deg, transparent 30%, rgba(3,20,42,.9)), url(${media.action})` }} /><div className="play-button"><Play fill="currentColor" /></div><div className="video-caption"><span>Video / Reel destacado</span><strong>Camp Experience<br />en acción <ArrowUpRight /></strong></div><div className="video-social"><span className="social-mark">IG</span> @campexperienceve</div></a></div></section>

      <section className="logos-section frame"><div className="section-label">05 / Respaldo internacional</div><div className="logos-grid"><div><h2>El estándar<br /><i>que inspira.</i></h2><p>La pasión argentina llega a Venezuela con el respaldo de una de las instituciones futbolísticas más reconocidas del mundo.</p><a className="under-link" href="#contacto">Recibe información <ArrowUpRight /></a></div><div className="logo-lockup"><img src={media.afa} alt="AFA Internacional" /><span>Metodología oficial</span></div><div className="logo-lockup light-card"><img src={media.tm} alt="TMXperience" /><span>Experiencia Venezuela</span></div></div></section>

      <section className="faq-section frame"><div className="section-label">06 / Preguntas frecuentes</div><div className="faq-grid"><h2>Todo lo que<br /><i>quieres saber.</i></h2><div className="faq-list">{faqs.map(([q, a], index) => <div className={openFaq === index ? 'faq-item active' : 'faq-item'} key={q}><button onClick={() => setOpenFaq(openFaq === index ? -1 : index)} aria-expanded={openFaq === index}><span>{q}</span><ChevronDown /></button>{openFaq === index && <p>{a}</p>}</div>)}</div></div></section>

      <section id="contacto" className="contact"><div className="frame contact-inner"><img src={media.afa} alt="AFA Internacional" /><div><div className="hero-kicker">Cupos limitados · Próxima edición</div><h2>Tu historia<br /><i>empieza aquí.</i></h2><a className="button orange" href="https://wa.me/584120000000" target="_blank" rel="noreferrer">Reserva tu cupo <ArrowUpRight /></a></div></div></section>
      <footer className="footer"><div className="frame footer-top"><div><a className="footer-name" href="#inicio">CAMP<span>EXPERIENCE</span></a><p>Fútbol que transforma.<br />Experiencias que quedan.</p></div><div className="footer-nav"><div><b>Explora</b><a href="#nosotros">Nosotros</a><a href="#programa">Programa</a><a href="#cronograma">Cronograma</a><a href="#sedes">Sedes</a><a href="#patrocinantes">Patrocinantes</a></div><div><b>Conecta</b><a href="https://www.instagram.com/campexperienceve/" target="_blank" rel="noreferrer">Instagram</a><a href="#contacto">WhatsApp</a><a href="#contacto">Contacto</a></div></div></div><div className="frame footer-bottom"><span>© 2025 Camp Experience Vzla</span><span>TMX × AFA Internacional</span></div></footer>
      {registrationCity && <RegistrationForm city={registrationCity} onClose={() => setRegistrationCity(null)} />}
    </main>
  )
}
